config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  get "about", to: "pages#about"
  resources :articles
  get "signup", to: "users#new"
  resources :users, except: [:new]
  get "login", to: 'sessions#new'
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  resources :categories, except: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  validates :title, presence: true, length: { minimum: 6, maximum: 100 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, length: { minimum: 3, maximum: 25 }
  validates_uniqueness_of :name
end

app/models/user.rb
class User < ApplicationRecord
  before_save {self.email = email.downcase}
  has_many :articles, dependent: :destroy
  validates :username, presence: true,
            length:{ minimum: 3, maximum: 25 }, 
            uniqueness: { case_sensitive: false }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, 
            length:{ maximum: 105 }, 
            uniqueness: { case_sensitive: false }, 
            format: { with: VALID_EMAIL_REGEX }

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user 
  end

  def require_user
    if !logged_in?
      flash[:alert] = "You must be logged in to perform that action"
      redirect_to login_path
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:show, :index]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  
  def show
  end

  def index
    @articles = Article.paginate(page: params[:page])
  end

  def new
    @article = Article.new
  end

  def edit
   
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:notice] = "Article was created Successfully"
      redirect_to @article
    else
      render 'new'
    end
    #render plain: @article.inspect this helps you find what are you sending to db
  end

  def update
    if @article.update(article_params)
    redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit([:title, :description])
  end

  def require_same_user
    if current_user != @article.user && !current_user.admin?
      flash[:alert] = "You can only edit your articles"
      redirect_to @article
    end
  end

end

app/controllers/categories_controller.rb
class CartegoriesController < ApplicationController
  def new
    @category = Category.new
  end

  def create
    @caterogy = Category.new(category_params)
    if @category.save
      flash[:notice] = " Successfull created "
      redirect_to @category
    else
      render 'new'
    end
  end

  def index
  end

  def show
  end
  
  def create
  end

  private

  def categories_params
    params.require(:category).permit(:name)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
        redirect_to articles_path if logged_in?
    end
    
    def about
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = "Logged in successfully"
      redirect_to user
    else
      flash.now[:alert] = "There was something wrong with your login details"
      render 'new'
    end

  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Logged out"
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_user, only: [:edit, :update]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def new
    @user = User.new
  end

  def index
    @users = User.paginate(page: params[:page])
  end

  def create
    @user= User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Welcome to the blog #{@user.username}, you have signed up"
      redirect_to articles_path
    else
      render 'new'
    end
  end

  def show
    @articles = @user.articles.paginate(page: params[:page])
  end

  def edit
    
  end

  def update
    
    if @user.update(user_params)
      flash[:notice] = "Your account was updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    @user.destroy
    session[:user_id] = nil if @user == current_user
    flash[:notice] = "Account and all articles deleted"
    redirect_to articles_path
  end

  private 
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
  
  def set_user
    @user = User.find(params[:id])
  end
  
  def require_same_user
    if current_user != @user && !current_user.admin?
      flash[:alert] = "You can only edit your user"
      redirect_to @user
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def gravatar_for(user, options = { size: 80 })
    email_address = user.email.downcase
    hash = Digest::MD5.hexdigest(email_address)
    size = options[:size]
    gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: "rounded shadow mx-auto d-block")
  end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_article.html.erb
<div class="container">
<% @articles.each do |article| %>
  <div class="card text-center">
    <div class="card-header font-italic">
      <%if article.user %>
      by <%= link_to article.user.username, user_path(article.user) %>
      <% end %>
    </div>
    <div class="card-body">
      <h5 class="card-title"><%= link_to article.title, article_path(article) %> </h5>
      <p class="card-text"><%= truncate(article.description, length:100 )%></p>
      <%= link_to "View", article_path(article), class: "btn btn-outline-success" %>
      <% if logged_in? && (article.user == current_user || current_user.admin?) %>
        <%= link_to "Edit", edit_article_path(article), class: "btn btn-outline-info" %> 
        <%= link_to "Delete", article_path(article), class: "btn btn-outline-danger", method: :delete, data: {confirm: "Are you sure?"} %>
        <%end %>
    </div>
  </div>
  <% end %>
</div>

app/views/articles/_form.html.erb
<div class="container">
<%= render 'shared/errors', obj: @article %>
<%= form_with(model: @article, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f|%>
<div class="form-group row">
    <%= f.label :title, class: "col-2 cold-form-label" %><br/>
    <%= f.text_field :title, class: "form-control shadow rounded"  %>
</div>

<div class="form-group row">
  <%= f.label :description %><br/>
  <%= f.text_area :description %> 
  </div>
<p>
<%=f.submit class: "btn btn-outline btn-lg" %>
</p>

<%end %>

<%= link_to "Cancel Edit and return",  articles_path%>
</div>

app/views/articles/edit.html.erb
<h1 class="text-center">Edit Article </h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1 class="text-center">Articles</h1>

<div class="digg_pagination">
    <%= will_paginate @articles, :container => false %>
  </div>

<%= render 'article' %>

<p><%= button_to 'Create New Article', new_article_path(@articles), method: :get %> </p>

<%= link_to "Home", root_path %>

<%= link_to "Bloggers", users_path %>

<div class="digg_pagination">
    <%= will_paginate @articles, :container => false %>
  </div>

app/views/articles/new.html.erb
<h1 class="text-center">Create a new Article </h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h1 class="text-center"><%= @article.title %></h1>
<div class="card text-center">
  <div class="card-header font-italic">
    by <%= @article.user.username if @article.user %>
  </div>
  <div class="card-body">
    <p class="card-text"><%= @article.description %></p>
  <% if logged_in? && (@article.user == current_user || current_user.admin? ) %> 
    <%= link_to "Edit", edit_article_path(@article), class: "btn btn-outline-info" %>
    <%= link_to "Delete", article_path(@article), class: "btn btn-outline-danger", method: :delete, data: {confirm: "Are you sure?"} %>
  <% end %>
  </div>
</div>

<%= link_to "Home", root_path %> |
<%= link_to "Return to all articles",  articles_path%>

app/views/categories/index.html.erb
<h1 class="text-center">Create a new Category</h1>

<div class="container">
<%= render 'shared/errors', obj: @category%>
<%= form_with(model: @category, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f|%>
<div class="form-group row">
    <%= f.label :name, class: "col-2 col-form-label text-light" %><br/>
    <%= f.text_field :name, class: "form-control shadow rounded"  %>
</div>

<div class="form-group row justify-content-center">
<%=f.submit class: "btn btn-outline-light btn-lg" %>
</p>
</div>
<%end %>

<%= link_to "Cancel Edit and return",  articles_path%>
</div>

app/views/layouts/_messages.html.erb
<div class="container">
<% flash.each do |name,msg| %>
  <div class="alert alert-<%= name == "notice" ? "success" : "danger" %>" role="alert">
  <%= msg %>
  </div>
<% end %> 
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="#">Navbar</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-expanded="false">
              Dropdown
            </a>
            <div class="dropdown-menu">
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">Something else here</a>
            </div>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled">Disabled</a>
          </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RoRPt</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
  </head>

  <body>

    <%= render 'layouts/messages' %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>This is the about page</h1>

app/views/pages/home.html.erb
<h1>This is the home page</h1>

<%= link_to "Articles", articles_path %> |

<%= link_to "About" , about_path %>

<%= link_to "Sign up!", signup_path, class: "btn btn-primary btn-lg" %>

<%= link_to "Log in", login_path, class: "btn btn-primary btn-lg" %>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %> <! -- if there are any errors */ -->
<div class="alert alert-danger alert-dismissible fade show" role="alert">
  <h4 class="alert-heading">The following errors occured </h4>
    <ul>
        <% obj.errors.full_messages.each do |msg| %>
          <li><%= msg %> </li>
        <%end%>
    </ul>
</div>  
<%end%>

app/views/users/_form.html.erb
<div class="container">
<%= render 'shared/errors', obj: @user%>
<%= form_with(model: @user, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f|%>
<div class="form-group row">
    <%= f.label :username, class: "col-2 col-form-label text-light" %><br/>
    <%= f.text_field :username, class: "form-control shadow rounded"  %>
</div>

<div class="form-group row">
  <%= f.label :email, class: "col-2 col-form-label text-light" %><br/>
  <%= f.email_field :email, class: "form-control shadow rounded" %> 
  </div>

  <div class="form-group row">
  <%= f.label :password, class: "col-2 col-form-label text-light" %><br/>
  <%= f.password_field :password, class: "form-control shadow rounded" %> 
  </div>
<div class="form-group row justify-content-center">
<%=f.submit(@user.new_record? ? "Sign Up" : "Update Account", class: "btn btn-outline-light btn-lg") %>
</p>
</div>
<%end %>

<%= link_to "Cancel Edit and return",  articles_path%>
</div>

app/views/users/edit.html.erb
<h1 class="text-center">Edit your profile</h1>
<%= render 'form'%>

app/views/users/index.html.erb
<h1 class="text-center">Bloogers</h1>
<div class="digg_pagination">
    <%= will_paginate @users, :container => false %>
  </div>
<div class="container">
<% @users.each do |user| %>
  <div class="card text-center">
    <div class="card-header font-italic">
     <%= link_to user.username, user %>
    </div>
    <div class="card-body">
      <h5 class="card-title"><%= link_to gravatar_for(user, size:150), user %> </h5>
      <p class="card-text"><%= pluralize(user.articles.count, "article") %></p>
      <%= link_to "View profile", user, class: "btn btn-outline-success" %>
      <% if logged_in? %>
        <% if user == current_user%>
        <%= link_to "Edit", edit_user_path(user), class: "btn btn-outline-info" %>
        <% end %>
      <%end%>
      <% if current_user.admin? %>
        <%= link_to "Delete", user_path(user), class: "btn btn-outline-danger", method: :delete, data: {confirm: "Are you sure you want to delete the FULL account?"} %>
      <%end%>
    </div>
  </div>
  <% end %>
</div>

<%= link_to "Bloggers", users_path %>

<div class="digg_pagination">
    <%= will_paginate @users, :container => false %>
  </div>

app/views/users/new.html.erb
<h1 class="text-center">Sign up for blog!</h1>
<%= render 'form'%>

app/views/users/show.html.erb
<h1 class="text-center"><%= @user.username %>'s profile</h1>

<%= gravatar_for @user, size:200 %>

<% if logged_in? && @user == current_user %>
<div class="text-center mt-4">
 <%= link_to "Edit your profile", edit_user_path(@user), class: "btn btn-outline-info" %>
 <%= link_to "Delete your user",  user_path(@user), class: "btn btn-outline-info text-danger", method: :delete, data: {confirm: "Are you sure ?"} %>
 <p><%= button_to 'Create New Article', new_article_path(@articles), method: :get %> </p>
 </div>
<%end%>

<div class="digg_pagination">
    <%= will_paginate @articles, :container => false %>
  </div>

<h3 class="text-center">Articles</h3>

<%= render 'articles/article' %> 

<div class="digg_pagination">
    <%= will_paginate @articles, :container => false %>
  </div>

  <%= link_to "Log out", logout_path, class: "btn btn-primary btn-lg", method: :delete%>